### ISSUE TITLE
Feature: Favoriting

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/software-engineering-daily-api#4]
Users need to be able to favorite posts. We need:
1. Route to favorite/unfavorite
2. A route to return the user's favorite

**Comment by andrewmarklloyd** [comment]
Currently working on adding the route to favorite and unfavorite. @TheHollidayInn do you want us to assign issues to ourselves?

**Comment by TheHollidayInn** [comment]
Sweet. Yea, feel free to claim the issue by posting or assigning yourself. There is not model at the moment, but voting works the same way as favoriting should.

**Comment by andrewmarklloyd** [comment]
Sounds good!

**Comment by andrewmarklloyd** [comment]
The Post model currently has a score which represents its aggregate upvotes and downvotes. Should a favorite increase the total score for a Post? If so then I'll just increment the total similar to the upvoting/downvoting use case. If not then I'll need to update the Post model to represent the total favorites. Going down that road, how should this impact the recommendations since the Raccoon API essentially only has like and dislike.

**Comment by TheHollidayInn** [comment]
1. Let's add a total favorites field rather than adjust to the score.
2. I am working on a few more recommendations engines we will use to incorporate favorites and viewed. Raccoon does a simply k-mean, and we will only use upvotes for that now.
