### ISSUE TITLE
API route for /favorite/{postId}

### ISSUE THREAD

**Issue by justinctlam** [SoftwareEngineeringDaily/software-engineering-daily-api#87]
I think it might be useful to have an API to get the favorite state of the specific postId.
Perhaps a /favorite/{postId}?

**Comment by joshmorel** [comment]
If we implement this route it should return:

* 204 No Content: if bookmarked/favorited by authenticated user
* 404 No Content: if not bookmarked/favorited by authenticated user

From the client perspective, would this or including the `bookmarked` attribute in GET /posts/{postId} be more helpful? 

#83 should be merged in develop soon, which will include a `bookmarked` attribute for the authenticated user for the array of posts (but not yet for individual /post{postId})

**Comment by justinctlam** [comment]
I can try using the api for #83 first. I’m just thinking how we would handle this if the user grabs the post first, then logs in. Then we will need to get the post again to get the bookmark, is that right?

**Comment by justinctlam** [comment]
I guess this would be the same as getting the user’s vote choice as well.

**Comment by joshmorel** [comment]
There will be a variety of information about the user-post relationship. This includes bookmarked status, votes, listened status, and more potential later (timestamp upon close maybe?).

We should decide on an ideal way to expose this to the client. If the user is authenticated, currently we have `upvoted`, `downvoted` and soon `bookmarked`. I think there are a few decisions worth considering from an api-perspective as we move forward.

The 1st is, should we explicitly group these elements into a `user` object. So for example you have:
   1) post { title: "something", etc: ..., user: {upvoted: true, downvoted: false, bookmarked: false, currentTimestamp: '11:10' } }
   1) instead of post { title: "something", etc..., upvoted: true, downvoted: false, bookmarked: false }

Both are fine, but I can imagine the former being easier to reason about as the scope of the app increases.

The 2nd is, what should the route be for getting this user specific info for a post/episode:
   1)  None, just return with GET /post or GET /post/{postId} as described in 1st option above
   1) Available separately through a GET /post/{postId}/user route
   1) Available through attribute specific routes --- GET /favorite/{postId}, /vote/{postId}, etc for the authenticated user

Of course, we can implement the 3rd as needed even if we adopt option 1 or 2.

**Comment by justinctlam** [comment]
I like #1, as the user scope makes it easier to understand and reason with.

For the second API, I like #2, because this will save bandwidth by not getting redundant data. Or maybe, give the option to get all of together or just the data we need. So either I can get the entire post with user data or just post or just user data.

**Comment by joshmorel** [comment]
As we move from MVP this might be a good opportunity to give Swagger Hub a try to map out what an our consistent API design might look like prior to more API development. I'll get something set up then let you know.

But since I'm here, for item 2, I think if we want user info only specific to a post/episode I think being very explicit with /posts/{postId}/user makes sense while for posts, we can have a query variable for /posts and /posts/{postId} to specific if we want the user info returned or not. No matter, I'll do a bit of thinking and research on best practice while getting the Swagger Hub design set-up.

**Comment by justinctlam** [comment]
Sounds like a plan. Thanks for the API support! : )

**Comment by justinctlam** [comment]
Hi, I saw there was a commit to return bookmark value when getting posts. But when I call the API I don't seem to see the value. Has this change been deployed? Just wanted to double check.
Thanks.

**Comment by jasonify** [comment]
@justinctlam  it has not been pushed (I don't think) :/

I've queued up a few changes that should go live on Monday. Sorry about that.
